/**
 * The HTTP half of PDF export — shared by the member route
 * (/api/pdf/<kind>/<id>) and the public one
 * (/api/pdf/shared/invoice/<token>), so both answer with identical
 * headers and neither can accidentally become cacheable.
 */

import type { PdfResult } from "./documents.ts";
import { PAGE_SIZES, type PageSizeName } from "./writer.ts";

/** `?size=letter` → US Letter; anything else (and nothing) → A4.
 *  A4 is the default because the product is global; Letter is one query
 *  param away for North America. */
export function requestedPageSize(request: Request): PageSizeName {
  const requested = new URL(request.url).searchParams.get("size");
  // hasOwnProperty, NOT `in`: `"__proto__" in PAGE_SIZES` is true, and
  // taking that branch would hand the layout an object with no width and
  // paint every coordinate as NaN.
  return requested &&
    Object.prototype.hasOwnProperty.call(PAGE_SIZES, requested)
    ? (requested as PageSizeName)
    : "a4";
}

/**
 * An attachment response for generated bytes.
 *
 * - `content-disposition: attachment` — a click downloads the file instead
 *   of navigating the tab into a viewer (the filename carries the invoice
 *   number / document slug, so a client's Downloads folder stays sane).
 *   The filename is ASCII by construction (lib/pdf/documents.slugify), and
 *   `filename*` repeats it UTF-8-encoded for RFC 5987 clients.
 * - `no-store` — documents are per-workspace and change as rows change;
 *   nothing between the app and the browser should keep a copy.
 */
export function pdfResponse(result: PdfResult): Response {
  const ascii = result.filename.replace(/[^\x20-\x7e]/g, "_").replace(/"/g, "");
  // A fresh ArrayBuffer-backed copy: Response wants BodyInit, and a
  // Uint8Array view into a larger buffer would send the whole buffer.
  const body = new Uint8Array(result.bytes);
  return new Response(body, {
    status: 200,
    headers: {
      "content-type": "application/pdf",
      "content-length": String(body.byteLength),
      "content-disposition": `attachment; filename="${ascii}"; filename*=UTF-8''${encodeURIComponent(
        result.filename
      )}`,
      "cache-control": "no-store, max-age=0",
      // Generated documents are never framed by anything.
      "x-content-type-options": "nosniff",
    },
  });
}
