"use server";

/**
 * Server actions for the /settings Team card (Step 15). Owner-only — the
 * UI hides these controls from members, the actions re-check the role
 * themselves as defense in depth, and RLS (is_workspace_owner on
 * team_invites) is the final gate either way.
 *
 * Delivery is copy-link by design: NO email is sent. The owner copies the
 * invite URL out of the pending list and sends it via their own channel.
 */

import { revalidatePath } from "next/cache";

import { createClient } from "@/lib/supabase/server";
import { isUuid } from "@/lib/utils";

export type TeamActionResult = { error?: string } | undefined;

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const INVITE_TTL_MS = 14 * 24 * 60 * 60 * 1000; // 14 days (spec)

/** Session + workspace membership (+role). Null when logged out or when
 *  no workspace exists yet (pre-onboarding). */
async function getMembership() {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { supabase, user: null, membership: null };

  const { data } = await supabase
    .from("workspace_members")
    .select("workspace_id, role")
    .eq("user_id", user.id)
    .order("created_at", { ascending: true })
    .limit(1)
    .maybeSingle();

  return {
    supabase,
    user,
    membership: (data ?? null) as {
      workspace_id: string;
      role: "owner" | "member";
    } | null,
  };
}

/**
 * Create a targeted, single-use invite for `email` (normalized to
 * lowercase). The token is generated by the table default; the UI reads
 * the fresh row back after revalidation and renders its copy link.
 */
export async function createTeamInviteAction(input: {
  email: string;
}): Promise<TeamActionResult> {
  const email = input.email?.trim().toLowerCase() ?? "";
  if (!EMAIL_RE.test(email)) {
    return { error: "Enter a valid email address." };
  }
  if (email.length > 254) {
    return { error: "That email address is too long." };
  }

  const { supabase, user, membership } = await getMembership();
  if (!user || !membership) {
    return { error: "Your session has expired. Please log in again." };
  }
  if (membership.role !== "owner") {
    return { error: "Only workspace owners can invite teammates." };
  }
  if (user.email?.toLowerCase() === email) {
    return {
      error: "That's your own address — you're already in this workspace.",
    };
  }

  const { error } = await supabase.from("team_invites").insert({
    workspace_id: membership.workspace_id,
    email,
    invited_by: user.id,
    expires_at: new Date(Date.now() + INVITE_TTL_MS).toISOString(),
  });

  if (error) {
    // Partial unique index: one pending invite per (workspace, email).
    if (error.code === "23505") {
      return { error: "There's already a pending invite for this email." };
    }
    return { error: error.message };
  }

  revalidatePath("/settings");
  return { error: undefined };
}

/** Revoke a pending invite — keeps the row as an audit trail (the
 *  share_links precedent). Idempotent; owner-gated. */
export async function revokeTeamInviteAction(input: {
  inviteId: string;
}): Promise<TeamActionResult> {
  if (!isUuid(input.inviteId ?? "")) {
    return { error: "Unknown invite." };
  }

  const { supabase, membership } = await getMembership();
  if (!membership) {
    return { error: "Your session has expired. Please log in again." };
  }
  if (membership.role !== "owner") {
    return { error: "Only workspace owners can revoke invites." };
  }

  const { error } = await supabase
    .from("team_invites")
    .update({ revoked_at: new Date().toISOString() })
    .eq("id", input.inviteId)
    .eq("workspace_id", membership.workspace_id);

  if (error) return { error: error.message };

  revalidatePath("/settings");
  return { error: undefined };
}
