"use server";

/**
 * Server actions for the /settings Team card (Step 15). Owner-only — the
 * UI hides these controls from members, the actions re-check the role
 * themselves as defense in depth, and RLS (is_workspace_owner on
 * team_invites) is the final gate either way.
 *
 * Delivery (Step 23, revised — plain SMTP via nodemailer): when the
 * SMTP_* env vars are set, the invite link is emailed to the invitee
 * through the project owner's own mail account (lib/invite-email).
 * Copy-link stays as the fallback — no SMTP config skips the email
 * silently (dev mode), and a failed send never blocks invite creation
 * (the row is durable; the UI gets a warning + the copy link).
 */

import { revalidatePath } from "next/cache";
import { headers } from "next/headers";

import { clearActiveWorkspaceIfPointingAt } from "@/lib/active-pointer";
import { sendInviteEmail } from "@/lib/invite-email";
import { getWorkspaceContext } from "@/lib/data/workspace-context";
import { createClient } from "@/lib/supabase/server";
import { isUuid } from "@/lib/utils";

export type TeamActionResult = { error?: string; warning?: string } | undefined;

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const INVITE_TTL_MS = 14 * 24 * 60 * 60 * 1000; // 14 days (spec)

/** Session + ACTIVE workspace membership (+role) via the Step-16
 *  resolver. Null when logged out or when no workspace exists yet. */
async function getMembership() {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { supabase, user: null, membership: null };

  const context = await getWorkspaceContext();

  return {
    supabase,
    user,
    membership: context
      ? { workspace_id: context.id, name: context.name, role: context.role }
      : null,
  };
}

/**
 * Create a targeted, single-use invite for `email` (normalized to
 * lowercase). The token is generated by the table default; the UI reads
 * the fresh row back after revalidation and renders its copy link.
 */
export async function createTeamInviteAction(input: {
  email: string;
}): Promise<TeamActionResult> {
  const email = input.email?.trim().toLowerCase() ?? "";
  if (!EMAIL_RE.test(email)) {
    return { error: "Enter a valid email address." };
  }
  if (email.length > 254) {
    return { error: "That email address is too long." };
  }

  const { supabase, user, membership } = await getMembership();
  if (!user || !membership) {
    return { error: "Your session has expired. Please log in again." };
  }
  if (membership.role !== "owner") {
    return { error: "Only workspace owners can invite teammates." };
  }
  if (user.email?.toLowerCase() === email) {
    return {
      error: "That's your own address — you're already in this workspace.",
    };
  }

  const expiresAt = new Date(Date.now() + INVITE_TTL_MS);
  const {
    data: invite,
    error,
  } = await supabase
    .from("team_invites")
    .insert({
      workspace_id: membership.workspace_id,
      email,
      invited_by: user.id,
      expires_at: expiresAt.toISOString(),
    })
    .select("token")
    .single();

  if (error) {
    // Partial unique index: one pending invite per (workspace, email).
    if (error.code === "23505") {
      return { error: "There's already a pending invite for this email." };
    }
    return { error: error.message };
  }

  // Best-effort email (Step 23) — no SMTP config skips it silently (dev
  // mode); a failure never blocks the already-created invite.
  let warning: string | undefined;
  const h = headers();
  const host = h.get("x-forwarded-host") ?? h.get("host");
  if (!host) {
    warning =
      "Invite created — but the email was skipped. Copy the link below and send it yourself.";
  } else {
    // x-forwarded-* under the platform; plain Host locally.
    const proto =
      h.get("x-forwarded-proto") ??
      (host.startsWith("localhost") || host.startsWith("127.")
        ? "http"
        : "https");
    const { data: me } = await supabase
      .from("profiles")
      .select("full_name")
      .eq("id", user.id)
      .maybeSingle();
    const sent = await sendInviteEmail({
      to: email,
      workspaceName: membership.name,
      inviterName: me?.full_name || user.email,
      inviteUrl: `${proto}://${host}/invite/${invite.token}`,
      expiresAt,
    });
    if (!sent.ok && sent.reason === "send-failed") {
      console.error("invite email failed:", sent.detail);
      warning =
        "Invite created — but the email couldn't be sent. Copy the link below and send it yourself.";
    }
  }

  revalidatePath("/settings");
  return { error: undefined, warning };
}

/** Revoke a pending invite — keeps the row as an audit trail (the
 *  share_links precedent). Idempotent; owner-gated. */
export async function revokeTeamInviteAction(input: {
  inviteId: string;
}): Promise<TeamActionResult> {
  if (!isUuid(input.inviteId ?? "")) {
    return { error: "Unknown invite." };
  }

  const { supabase, membership } = await getMembership();
  if (!membership) {
    return { error: "Your session has expired. Please log in again." };
  }
  if (membership.role !== "owner") {
    return { error: "Only workspace owners can revoke invites." };
  }

  const { error } = await supabase
    .from("team_invites")
    .update({ revoked_at: new Date().toISOString() })
    .eq("id", input.inviteId)
    .eq("workspace_id", membership.workspace_id);

  if (error) return { error: error.message };

  revalidatePath("/settings");
  return { error: undefined };
}

/**
 * Change a member's role in the ACTIVE workspace (Step 22 — role
 * management, the Step 15 follow-up). Invites only ever grant
 * 'member', so promoting is the only path to an owner role.
 *
 * Guards (defense in depth — the UI hides the same cases, and the
 * Step-22 UPDATE policy on workspace_members enforces them at the DB
 * level):
 *   * owner-gated (role check here + is_workspace_owner in RLS);
 *   * NO SELF-ROLE-CHANGES — "leaving" (including self-demotion) is a
 *     different action (recorded cut, like Step 21's self-removal);
 *   * NO LAST-OWNER DEMOTION — a workspace must always keep at least
 *     one owner.
 */
export async function changeMemberRoleAction(input: {
  userId: string;
  role: "owner" | "member" | "viewer";
}): Promise<TeamActionResult> {
  if (!isUuid(input.userId ?? "")) {
    return { error: "Unknown member." };
  }
  if (
    input.role !== "owner" &&
    input.role !== "member" &&
    input.role !== "viewer"
  ) {
    return { error: "Unknown role." };
  }

  const { supabase, user, membership } = await getMembership();
  if (!user || !membership) {
    return { error: "Your session has expired. Please log in again." };
  }
  if (membership.role !== "owner") {
    return { error: "Only workspace owners can change roles." };
  }
  if (user.id === input.userId) {
    return {
      error:
        "You can’t change your own role — use Leave on your own row instead.",
    };
  }

  // The target's membership (RLS-scoped to our workspaces; a non-member
  // or foreign id resolves to no row).
  const {
    data: target,
    error: targetError,
  } = await supabase
    .from("workspace_members")
    .select("user_id, role")
    .eq("workspace_id", membership.workspace_id)
    .eq("user_id", input.userId)
    .maybeSingle();

  if (targetError) return { error: targetError.message };
  if (!target) {
    return { error: "That person is no longer a member of this workspace." };
  }

  // Idempotent no-op when the role is already what was requested.
  if (target.role !== input.role) {
    // Last-owner guard: demoting the sole owner would leave the
    // workspace without one.
    if (target.role === "owner" && input.role !== "owner") {
      const { count, error: countError } = await supabase
        .from("workspace_members")
        .select("user_id", { count: "exact", head: true })
        .eq("workspace_id", membership.workspace_id)
        .eq("role", "owner");
      if (countError) return { error: countError.message };
      if ((count ?? 0) <= 1) {
        return {
          error: "You can’t demote the last owner of a workspace.",
        };
      }
    }

    const { error } = await supabase
      .from("workspace_members")
      .update({ role: input.role })
      .eq("workspace_id", membership.workspace_id)
      .eq("user_id", input.userId);

    if (error) return { error: error.message };
  }

  revalidatePath("/settings");
  return { error: undefined };
}

/**
 * Remove a member from the ACTIVE workspace (Step 21 — closes out the
 * Step 15 team feature). The owner-only DELETE policy on
 * workspace_members has existed since Step 2; this is the first app
 * surface that uses it.
 *
 * Guards (defense in depth — the UI hides the same cases):
 *   * owner-gated (role check here + is_workspace_owner in RLS);
 *   * NO SELF-REMOVAL — "leaving a workspace" is a different action
 *     (recorded cut, not built here);
 *   * NO LAST-OWNER REMOVAL — a workspace must always keep at least
 *     one owner (transferring ownership is role management, future).
 */
export async function removeMemberAction(input: {
  userId: string;
}): Promise<TeamActionResult> {
  if (!isUuid(input.userId ?? "")) {
    return { error: "Unknown member." };
  }

  const { supabase, user, membership } = await getMembership();
  if (!user || !membership) {
    return { error: "Your session has expired. Please log in again." };
  }
  if (membership.role !== "owner") {
    return { error: "Only workspace owners can remove members." };
  }
  if (user.id === input.userId) {
    return {
      error:
        "You can’t remove yourself — use Leave on your own row instead.",
    };
  }

  // The target's membership (RLS-scoped to our workspaces; a non-member
  // or foreign id resolves to no row).
  const {
    data: target,
    error: targetError,
  } = await supabase
    .from("workspace_members")
    .select("user_id, role")
    .eq("workspace_id", membership.workspace_id)
    .eq("user_id", input.userId)
    .maybeSingle();

  if (targetError) return { error: targetError.message };
  if (!target) {
    return { error: "That person is no longer a member of this workspace." };
  }

  // Last-owner guard: count the workspace's owners before deleting.
  if (target.role === "owner") {
    const { count, error: countError } = await supabase
      .from("workspace_members")
      .select("user_id", { count: "exact", head: true })
      .eq("workspace_id", membership.workspace_id)
      .eq("role", "owner");
    if (countError) return { error: countError.message };
    if ((count ?? 0) <= 1) {
      return { error: "You can’t remove the last owner of a workspace." };
    }
  }

  const { error } = await supabase
    .from("workspace_members")
    .delete()
    .eq("workspace_id", membership.workspace_id)
    .eq("user_id", input.userId);

  if (error) return { error: error.message };

  // Stale-pointer cleanup (Step 25): the removed person's
  // active_workspace_id may name THIS workspace — clear it now so the
  // row matches reality immediately (the resolver would self-heal their
  // next visit regardless). Best-effort; never blocks the removal.
  await clearActiveWorkspaceIfPointingAt(
    supabase,
    input.userId,
    membership.workspace_id
  );

  revalidatePath("/settings");
  return { error: undefined };
}

/** Leave the ACTIVE workspace (Step 26 — the self-removal half of the
 *  Step-21 feature). Anyone may leave except the workspace's last owner
 *  (the same invariant as removal/demotion: a workspace keeps one
 *  owner). The DB enforces all of it again (self-delete policy +
 *  BEFORE DELETE last-owner guard + the pointer-hygiene trigger), so
 *  this action's guards are defense in depth. */
export async function leaveWorkspaceAction(): Promise<TeamActionResult> {
  const { supabase, user, membership } = await getMembership();
  if (!user || !membership) {
    return { error: "Your session has expired. Please log in again." };
  }

  // Last-owner guard mirrors the DB trigger (Step 22 precedent).
  if (membership.role === "owner") {
    const { count, error: countError } = await supabase
      .from("workspace_members")
      .select("user_id", { count: "exact", head: true })
      .eq("workspace_id", membership.workspace_id)
      .eq("role", "owner");
    if (countError) return { error: countError.message };
    if ((count ?? 0) <= 1) {
      return {
        error:
          "You can’t leave — you’re the workspace’s last owner. Promote someone else first (or delete the workspace from the Danger zone).",
      };
    }
  }

  const { error } = await supabase
    .from("workspace_members")
    .delete()
    .eq("workspace_id", membership.workspace_id)
    .eq("user_id", user.id);

  if (error) return { error: error.message };

  // Best-effort pointer hygiene (the DB trigger is authoritative).
  await clearActiveWorkspaceIfPointingAt(
    supabase,
    user.id,
    membership.workspace_id
  );

  // The whole shell changes (switcher, every page's scoping) — and with
  // no membership left the (app) layout redirects to /onboarding.
  revalidatePath("/", "layout");
  return { error: undefined };
}
